### ISSUE TITLE
How configuration matches CustomCasSecurityConfiguration HttpSecurity

### ISSUE THREAD

**Issue by rafaelcastrocunha** [kakawait/cas-security-spring-boot-starter#107]
```java
public class CasConfiguration extends CasSecurityConfigurerAdapter {
       @Override
	public void configure(HttpSecurity http) throws Exception {
		http.authorizeRequests().antMatchers("/testServide/**").permitAll()
               .anyRequest().authenticated();
	}
}
```

With this configuration, it still requires testService authentication.  Am I implementing correctly? I want this service not to require authentication.

**Comment by gouldner** [comment]
Do you have a typo ?  "/testServide/**")  doesn't match testService

**Comment by kakawait** [comment]
@rafaelcastrocunha could you confirm that is not a typo error as @gouldner suggested ?

**Comment by gouldner** [comment]
@rafaelcastrocunha This solved my issue with antMatchers also.
For some reason extending CasSecurityConfigurerAdapter breaks all types of matchers.

So I changed to your technique of extending WebSecurityConfigurerAdapter and calling CasHttpSecurityConfigurer.cas().configure(http);

So your original code would have worked the same way if you did this.
```
public class CasConfiguration extends WebSecurityConfigurerAdapter {
       @Override
	public void configure(HttpSecurity http) throws Exception {
		http.authorizeRequests().antMatchers("/testServide/**").permitAll()
               .anyRequest().authenticated();
               CasHttpSecurityConfigurer.cas().configure(http);
	}
}
```


@kakawait is this a bug or by design?

**Comment by rafaelcastrocunha** [comment]
Thank you @gouldner
