### ISSUE TITLE
PGT ticket

### ISSUE THREAD

**Issue by coskundeniz89** [kakawait/cas-security-spring-boot-starter#53]
Hi @kakawait . I set security.cas.service.path.proxy-callback= /j_spring_cas_security_proxyreceptor. After this my app throw this 

`There was an unexpected error (type=Unauthorized, status=401).
Authentication Failed: The supplied proxy callback url 'https://localhost:8443/j_spring_cas_security_proxyreceptor' could not be authenticated. Either 'https://localhost:8443/j_spring_cas_security_proxyreceptor' cannot be reached, it is not allowed to exercise proxy authentication.`

How can i get pgt ticket for connect other cas-protected-apps?

**Comment by kakawait** [comment]
It seems that your CAS server is not able to reach https://localhost:8443/j_spring_cas_security_proxyreceptor.

Does your CAS server is on same machine (and not inside VM or container) ?

**Comment by coskundeniz89** [comment]
Yes you are true. I tried this without container, pgt work. But what is problem, i cant understand.

**Comment by kakawait** [comment]
CAS protocol defined that to send `PGT` CAS server call (!= respond to request) client, that means CAS server will create http connection using it's own http client to send `PGT` to the URL defined in _proxy callback_. But your proxy callback, if you don't change default conf, will be on `localhost` since you're connecting to your service with `https://localhost:8443`. But `localhost` inside CAS server container is not the same localhost from your host machine, that why CAS server can't reach your callback URL. 

You must use a resolvable _external_ domain name. If you're using docket for Mac you may find some solution by using https://docs.docker.com/docker-for-mac/networking/#per-container-ip-addressing-is-not-possible

In my personal use case I created an `lo0` alias different to 127.0.0.1 to solve that issue and I used that IP

**Comment by coskundeniz89** [comment]
Ok I understand @kakawait thanks for everything.

**Comment by kakawait** [comment]
I will add more doc when I will provided docker sample
